### ISSUE TITLE
Action-SC-2017-38 Revise SoR

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#209]
Develop a revised Statement of Requirements that will inform the work on options 1 and 4 for the new architecture and the associated estimates.  The intention is to assist European Dynamics @NMichas to develop the revised SoR by:
- providing a few days concentrated effort from @woollattd and @benjaminsaclier in Athens to update the old SoR docs and specs into a first cut new SoR.
- circulating the first cut around the relevant subject matter experts across the rest of the Association and updating as we go
- for European Dynamics to use this to work up the report on options 1 and 4 proposals/estimates in time for the SC in early June 2017.

**Comment by woollattd** [comment]
The basic requirements still stand, but there are some improvements that I think should also be considered to create a more rounded version of OpenWIS.
I have some initial thoughts about what I would like to see:
1. Better metadata management 
eg OpenWIS/openwis4#41, OpenWIS/openwis4#42, OpenWIS/openwis4#32)
2. better subscription process and subscribing to more than one at a time
eg OpenWIS/openwis4#58
3. better data delivery
4. simple anf fast install OpenWIS/openwis4#107
5. offer alternative Security Services (at least one simple and one more robust and complex)
6. Inspire capable

Anyone else have something specific to add.
Obviously at the early stages some may need to come later, but we may still need to have these in mind so that they can be added, more easily, later.

**Comment by jeffery1960** [comment]
1) To help metadata management, a simple export/import mechanism to enable bulk metadata changes would be really useful.
2) Defintely needs to state that it must be WIS 1.0 **and** WIS 2.0 compliant.

**Comment by solson-nws** [comment]
For metadata, I would add increased visibility to wider audience.  In principle, I'm thinking of a authoritative cloud-based solution for the metadata part that is a shared resource.  One that's public so search engines like google, etc and discover metadata artifacts and open it up to a wider spectrum of folks.

**Comment by lmika-bom** [comment]
One important thing is to allow project implementers to write and deploy their own local data sources (and maybe dissemination).  Not sure which technology stack is being planned but if we are going with something similar to what the PoC used (i.e. OSGi within a Kafka container), then using OSGi modules seems like a natural approach to allowing this.  It will just need a well defined interface.

**Comment by woollattd** [comment]
Another one might be to allow metadata to belong to 2 categories.
I.e. ECMWF metadata can belong to its own category (DCPC-ECMWF) as well as WIS-GISC-EXETER.
This enables easier management of their metadata on the GISC, and is still included for harvesting by other GISCs. It may also improve user searches as they are able to just select results from DCPC-ECMWF.

**Comment by lmika-bom** [comment]
Something to think about if we're going to rebuild OpenWIS from the ground up: do we want stopgap metadata?  My understanding of this is that this was mainly used to allow users to access the data associated with the metadata that hasn't been created yet.  However, it was not necessarily a popular approach to this problem.

Ditching stopgap metadata will mean that we will need to find another way for users to get data for datasets that don't have metadata yet.

**Comment by woollattd** [comment]
I think we should drop stop-gap metadata. We currently have around 2000 of these on the Exeter GISC. With no management of this metadata it will always remain with no real information, which is of no help for a search. Since we all upload the global data to the cache on our own GISCs, we are the ones choosing what to send. Data without metadata shouldn't be ingested. We should have monitoring to keep track of data that doesn't get ingested due to no metadata, we can then remove the routing for these should any find their way there. I remember DWD commenting on this about openwis, and said we shouldn't do it. I agree. But is there a real use case to keep stop-gap metadata functionality?

**Comment by rogers492** [comment]
So what is the use case where someone can provide data but they can't provide metadata?

**Comment by jeffery1960** [comment]
Hi Dom,

I totally agree – the WIS Specs don’t require stop gap metadata to be created.  Use Case B.3 covers what is required - the GISC/DCPC must wait two minutes before confirming there is no metadata.  If we don’t create stop gap metadata the system must clearly log all data that arrives with no associated metadata record.

Once identified in this way, the data can be removed from the data feed to the GISC/DCPC, and contact can be made with the data owner to request that suitable metadata is provided.

Cheers,

Duncan
--------------------------------------------------------------------------------------
Duncan Jeffery  BSc (Open) MBCS
MSS Team Leader
Met Office  Fitzroy Road  Exeter  Devon  EX1 3PB  United Kingdom
Tel: +44 (0)1392 886052  Fax: +44 (0)1392 885681
E-mail: duncan.jeffery@metoffice.gov.uk<mailto:duncan.jeffery@metoffice.gov.uk>   Website http://www.metoffice.gov.uk
Our magazine Barometer is now available online at http://www.metoffice.gov.uk/barometer/

**Comment by benjaminsaclier** [comment]
Yes agree, we don't need stop gap. But we must log data without any associated metadata and have an admin option to configure if we want or not store these data in a temporary directory (in case of investigation)

**Comment by woollattd** [comment]
A couple more from Steve Foreman (bumped into him at the hotel I was staying at in Athens)
1) Allowing search of the GEOSS catalogue (the SRU server is on the  "node to use" drop-down on page: http://www.wmo.int/pages/prog/www/WIS/wissruform.html)

2) Display the CAP alerts from countries in the GISC's AMDCN - (the feeds for each country can be found from the register of alerting authorities - https://alerting.worldweather.org/ )

**Comment by woollattd** [comment]
Another one from Steve Foreman:

one further thing that I forgot last week.

Members (such as New Zealand) are using GISC SRU search to produce listings of metadata records from the WIS catalogue to avoid having to hold their own catalogue. The OpenWIS implementation of SRU does not return a link to the cached copy of information. It would really increase the functionality if that link could be included.
