### ISSUE TITLE
OPP-6: WIS Djibouti

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#309]
**OPP-6: WIS Djibouti (working title)**

1. **Introduction**
    1. The [OpenWIS Association](http://openwis.github.io/openwis-documentation/) hosts multiple open source software development projects that support or enable the exchange of global meteorological information. 
    2. We use the [GitHub](https://github.com/OpenWIS) platform for our collaborative development. The rules and expectations for participating in an OpenWIS® Project are defined in the [Technical Rules](http://openwis.github.io/openwis-documentation/tr/) and the [Code of Conduct](http://openwis.github.io/openwis-documentation/conduct/). 
    3. The basic [governance](http://openwis.github.io/openwis-documentation/structure/governance.html) of the OpenWIS Association is laid out in the Articles of Association and the Internal Rules.

2. Purpose
    1. This charter establishes the foundation for the project team to begin developing, through a pilot project, the next iteration of the OpenWIS core software, by outlining the scope of this pilot project, identifying the contributing members and defining their responsibility. 
    2. Scope of Authority
        This task team is charged with conducting a pilot study on the future WMO Information System, often referred to as WIS 2.0.
    3. Authority
        The authority for this project comes from the OpenWIS Steering Committee (SC), on recommendations from the OpenWIS TC.  Outcomes from this and other pilot studies provide insight into WIS 2.0 specifications, and may ultimately factor into an architectural design and overall OpenWIS 5 plan with timelines.

3. Pilot Project Overview
Overview of pilot study task.
    1. Pilot Project Statement of Need or User Stories
        1. Imagine a WIS based on a set of common standards layered on top of each other and in which all data is stored in the Cloud as static files,
            - eg: TCP/IP, HTTP, URL. 
        2. Imagine that access to this WIS is easy, even on basic infrastructure, 
            - eg: internet only.
        3. Imagine that finding the data you want through common commercial search engines is simple and does not rely on a deep understanding of complex metadata, 
            - eg: because the metadata is stored as tags in human readable web-pages and is routinely indexed by web crawlers.
        4. Imagine that making new static file data available through WIS and ensuring that it's simple metadata gets indexed automatically is easy, even on basic infrastructure.
        5. Imagine that, once you have found the data you are looking for, subscribing to updates or routine delivery of that data is easy.
        6. Imagine that you have to demonstrate the concept of such a WIS to the TECO conference in early 2018 and that you have to easily convince the audience of the benefits such a WIS would bring.
    2. Pilot Project Scope
        1. Create a demonstration prototype that is suitable for presentation at TECO 2018 by a member of the SC.
        2. The Project team is responsible for: 
            - Development of the demonstration prototype software
            - Delivery of a package that will be suitable for demonstration at TECO
            - Any documentation or training required to deliver the demonstration
            - Any supporting infrastructure required to do the demonstration
            - Provision of realistic data for the demonstration.
        3. Pilot Project Goals
            - Demonstrate aspects of the future WIS 2.0 concept
            - Gain support at TECO for the whole WIS 2.0 concept, or at least significant aspects of it.
        4. Pilot Project Deliverables
            - Provide a bulletized list of expected deliverables for the Project Task:
            - TBD
            - TBD

4. Roles and Responsibilities:

Resource Name | Organization | Role | Responsibility | Time period resource needed for
| - | - |- | - | - |
Resource_A | Org_A | Role_A | Responsibility_A | Period_A
Resource_B | Org_B | Role_B | Responsibility_B | Period_B
	   
5. Milestones & Schedule

| Project Milestone | Begin Date | End Date |
| - | - | - |
Milestone 1  | YYYY/MM/DD | YYYY/MM/DD	   
Milestone 2  | YYYY/MM/DD | YYYY/MM/DD

6. Configuration Management Process
    - Define process for checking in/out code associated with pilot study

7. Communication and Reporting
    - Frequency and mode of team meetings, squad/team names, GitHub IDs etc
    - Define interactions with PMC including reports at PMC meetings
    - Define interactions with TC
        - Final report/briefing on pilot study findings and recommendations

**Comment by rogers492** [comment]
From @tg4444 :+1: Subject: Concerning Djibouti

We have already began investigating the AWS features required for the Djibouti pilot implementation, but before we delve any further, I want to make sure that our understanding is correct.

From the issue description - and based on my current understanding of OpenWIS - I came up with the following system requirements. Please correct/enrich this list:
    - R1. All data/metadata storage and processing occurs on AWS/RDS 
    - R2. There exists a back-end user interface for the Djibouti administrator to upload new data/metadata 
    - R3. No data/metadata editing will occur 
    - R4. Once the metadata is uploaded to the system, an HTML page is dynamically generated (by using an XSD maybe?) and that page will be available to search engines.
    - R5. The HTML page mentioned above will also contain a link that will forward users to another page, in which they will be able to subscribe to data, or manually download it.
    - R6. Subscription dissemination will take place though FTP and email.
    - R7. The data for subscriptions will be forwarded to the end-users as soon as they are uploaded by the Djibouti administrator (i.e. no time-based subscriptions).

Apart from the list of requirements, there are some questions I would like to ask regarding this pilot.
Q1. As far as I know, there is no location information (i.e. Country/Region/City) within the metadata, except from the longitude/latitude bounding box.
    If this is the case, how would someone wanting to find metadata for UK, Exeter be able to do so, based on Google, without knowing the exact "ID" of the metadata?
Q2. Even if we were able to provide location information, if someone wanted to subscribe to the whole UK data, he would need to click through 30 thousand pages in order to do so.
    Is this the desired functionality?
Q3. In order to provoke search engines into indexing and ranking our dynamically-generated HTML pages, we need to link towards them from other web-pages.
    An old common practice was to create a static web-page with hidden links to the dynamic pages, and have google go through that one.
    Search engines are now smart enough to ignore such pages.
    Do you have any preference on where the dynamic pages could be linked, or would you like us to research options?
Q4. Even with the dynamic pages being indexed, unless their content differs substantially, google will likely only show one result, and add a link at the bottom saying something like
    "There are 150,000 omitted results similar to this one. Click here if you want to search again including those results".
    If we want to make these pages look more different, a greater percentage of custom content should be displayed.
    Do you have any preference on where the dynamic pages could be linked, or would you like us to research options?

**Comment by 6a6d74** [comment]
Hi - I've tried to put a narrative in place around this project. See below. 

@tg4444 : I will try to answer your questions tomorrow...

---
​
**OpenWIS Djibouti**
 
[see Spatial Data on the Web Best Practices for recommended implementation patterns - https://www.w3.org/TR/sdw-bp/]

Mouktar is responsible for recording weather observations in the Tadjourah region of Djibouti. Data is collected for a number of locations:

* Tadjoura Port
* Lac Assal
* Dorra
* Assa Gaïla

Each day, observation data is sent to Mouktar via SMS message. Mouktar enters the information for each location into a separate tabular data file (CSV format) and copies the updated files to his Web server to publish the data online.

[note: alternatively, these CSV files may be pushed to AWS S3 to achieve the same outcome]
Mouktar has been collating this data for several years and has created a valuable timeseries of observation data for these locations.

[note: it would be useful and illustrative to include some GUI components to interact with the CSV content.]

Each of the four published CSV files are datasets that are registered on the WIS - indicating that these are authoritative datasets provided with the approval of Djibouti's Permanent Representative to WMO.

Mouktar has created a Web page describing each dataset - providing metadata in a human readable form. Mouktar has specified that this data is available as "Essential" data under WMO data policy: openly accessible and free to use without restriction. Each Web page also contains structured markup (embedded JSON-LD <script> using the schema.org vocabulary) providing machine-readable metadata.

[note: details of the structured markup need to be developed; should we encourage use of terms from http://codes.wmo.int ?]

[note: schema.org markup could be automatically generated from the CSV file - see https://www.w3.org/TR/tabular-data-primer/ and https://www.w3.org/TR/csv2json/#example-events-listing]

[note: at this point, Mouktar's 'catalogue' is a simple set of Web pages - this could be enhanced by providing search facilities across his portfolio of datasets; e.g. a Web page for humans and Open Search / OGC CSW3 (?) for software agents ... it would be interesting to provide a simple deployable component for data publishers to enrich their data portal]

Mouktar is relying on commercial search engines to make these datasets discoverable. He has created a site-map and registered it with the search engines, inviting them to crawl and index the Web-site.

[for more information on working with commercial search engines to expose geospatial data, see https://github.com/geo4web-testbed/topic3/wiki]

Additionally, Mouktar has registered these datasets with WIS as authoritative data. Following the pattern used by commercial search engines, the site-map is registered with the "Authoritative WIS Catalogue".

The "Authoritative WIS Catalogue" periodically crawls the registered Web sites, extracts the pertinent information from the structured markup and creates/updates a record for each registered dataset (or other resource).

[note: the Authoritative WIS Catalogue could be simply implemented using Elastic Search - harvesting JSON and indexing the content]

[note: the Authoritative WIS Catalogue could harvest from Open Search / OGC CSW3 end-points at each site- but this puts a burden on the data publisher to provide these services. Site-maps are simpler and proven to work]

---

Mohamed is trying to find out how the weather patterns have changed over the previous 5 years. He enters his keywords into Google and discovers the observation data collated by Mouktar.

[note: need to think about how a plain Google search can be optimised to find this content]

---

Dave is trying to find authoritative weather observation data for 2015-2017 in the horn of Africa. 

Dave uses a Web application to query the Authoritative WIS Catalogue specifying geographic location, time-period [and the specific physical parameters] he is interested in.

The Authoritative WIS Catalogue presents a list of datasets matching his search criteria. Summary information is provided for each dataset, including links to the source CSV files published by Mouktar and the corresponding Web pages.

---

Mouktar's colleague Mariam asks if she can subscribe to changes in the weather observation datasets.

>>> add more details about use of AMQP etc.

**Comment by remygiraud** [comment]
The broker envisaged is rabbitMQ. it is a very good multi protocol broker. However, it is fairly difficult to use. On a test environment based on MQTT only, I would suggest using mosquitto. MQTT only, fairly basic, but easy to install.

**Comment by tg4444** [comment]
I have some questions to ask regarding the WIS Djibuti pilot, and I was wondering whether to ask them here, or add them as issues in the new repo we have for the pilot.
I'm afraid that adding a lot of information in this thread will only make sorting through it more complex.
Please let me know how you want me to proceed.

**Comment by 6a6d74** [comment]
Continued development of OpenWIS Djibouti narrative...

----

Mariam is needs to incorporate weather observation data into her weather forecast model verification analysis. Downloading the CSV file each day and extracting the new observation is cumbersome. She asks Mouktar if there is a way that he can automatically disseminate the new weather observation to her.

Moutktar recalls that the regional data sharing hub [_not official terminology_] operate a reliable & highly-available pub-sub messaging infrastructure. 

Mouktar contacts his colleague Omar from the regional centre and asks for a new queue to be set up for each of the four locations from which observation data is collected*.

[* in due course, we will need to investigate whether it is appropriate to create one queue for all four locations, or use individual queues - but for this pilot application a queue per observation location will suffice] 

Omar duly sets up the four new queues as requested. Each one is considered to be a data service that must be registered on WIS. With Mouktar's assistance to describe the data, Omar creates a new Web page for each data service, describing the data available, the data license, how long data is retained on the queue, how to access it and how _authorised_ users can upload new data. These Web pages also contain structured JSON-LD <script> providing machine-readable metadata.

Omar adds these new pages to his existing site-map thereby enabling commercial search engines to crawl and index the new content. Similarly, the Authoritative WIS Catalogue will be able to find these new Web pages, extract the relevant metadata and create new records for the data services. 

Omar informs Mouktar that he, or his application must be authorised to publish content onto the new queues. Omar provides Mouktar with a list of trusted Identity Providers (e.g. eduGain, Google etc.) through which he can authenticate.

Mouktar already has an account with one of the Identity Providers, and configures his client application to authenticate using those credentials.

Mouktar uses his client application* to enter new data onto the relevant queues. He verifies with Omar that all is working OK.

[* I imagine this to be as simple as writing a tweet using an App or a web page]

Mouktar tells Mariam that the new data services / message queues have been set up and points her to the Authoritative WIS Catalogue where they are described. 

Mariam finds the information in the Authoritative WIS Catalogue, which refers her to the Web pages set up by Omar for more details. Therein she learns how to [configure her application to] subscribe to the new data services / message queues.

Using her client application* Mariam subscribes to the new data services / message queues.

[* for example, a Web-based application that simply allows her to "follow" (as in Twitter) the relevant queues and write the data to disk for local processing]

Mariam begins receiving messages* in near-real time, incorporating the data into her verification system.

[* in this case, we could embed the data in the message itself; it's just a line from a CSV file - but we should consider what to do regarding larger data, e.g. notification that new data is available for collection / in-situ use etc.] 

Some weeks go by with Mouktar's observation data messages being automatically disseminated to Mariam. Unfortunately, Mariam's client application suffers a system outage and loses data for the previous 3-days.

Mariam resolves the system outage and then reconfigures her client application to request data upto 3-days old to be resent.

Once  Miriam's application has caught up with the back-log, it continues to receive data as it arrives

**Comment by 6a6d74** [comment]
**Extension point: automated update of CSV files**

Mouktar notes how successful Mariam has been automatically ingesting observation data messages into her verification system. 

Mouktar wants to save himself some time by not having to manually update the CSV files with new data each time a new observation arrives.

Mouktar writes a simple Python script* which subscribes to the data services / message queues published by Omar and appends the appropriately formatted message content to the CSV file. The CSV file is automatically re-published (thanks to the Web server configuration), thereby automating one of Mouktar's many tasks.  

[* Python seems like an appropriate tool for this kind of hacking - other ideas welcome!]

**Comment by 6a6d74** [comment]
**Extension point: value added service based on threshold exceedance on multiple consecutive days**

(note: I am not a meteorologist - so this example might not make any practical sense, alternative scenarios welcome!)

Mouktar is keen for the data he is curating to deliver value to the citizens of Djibouti. From discussions with colleagues, he is made aware that agricultural crops are being damaged through exposure to extended dry periods. In many cases, the crop failure could be mitigated by increasing the amount of watering provided through irrigation.

Field experimentation by the University of Djibouti states that if the temperature exceeds X and humidity is lower than Y for 3 consecutive days, then crop damage can be reduced by increasing irrigation water-flow by 10%.

Mouktar contacts the University of Djibouti and suggests that a simple App is created to notify farmers when this situation occurs. Hugo, a software engineer from the university helps develop the App [e.g. using a framework like If This Then Than ([IFTTT](https://ifttt.com/))] that automatically publishes a tweet* when these conditions occur. Mouktar coordinates with his colleagues to publicise the Twitter account and provide authoritative Web pages with guidance about what the farmers should do when these conditions occur.

[*using Twitter is just one idea - the key point is that we want alter notifications to reach the community, ideally without Mouktar and co. having to send SMS messages to individual subscribers]

**Comment by 6a6d74** [comment]
**Extension point: graphical interaction with CSV data**

Based on feedback from his community, Mouktar understands that many people find it difficult to work with the CSV data as they must download it before being able to visualise the changes.

Mouktar finds a standard JavaScript library for visualising CSV data and creates a new Web page that includes these data visualisations.

Mouktar updates the Web pages that describe the dataset, referring to these new data visualisation pages and thereby helping potential users discover the new functionality.

**Comment by 6a6d74** [comment]
**Extension point: **

**Comment by NMichas** [comment]
Thanks a lot for the updates; it is very useful fleshing out the UCs in order to have a successful PoC. A few questions/remarks:

1/ "Moutktar recalls that the regional data sharing hub [not official terminology] operate a reliable & highly-available pub-sub messaging infrastructure."
Q: Does this mean that we introduce an additional "regional data sharing hub" (RDSH) component into the architecture?

2/ "Mouktar contacts his colleague Omar from the regional centre and asks for a new queue to be set up for each of the four locations from which observation data is collected*."
Q: If RDSH is our own software, we could automate this process (e.g. Mouktar has been given appropriate privileges to create the queues himself using a high-level web UI)

3/ "[* in due course, we will need to investigate whether it is appropriate to create one queue for all four locations, or use individual queues - but for this pilot application a queue per observation location will suffice]"
Q: We need to think whether it is/will be possible to hierarchically structure OpenWIS data and what this hierarchy should be/look like. If there is a hierarchy that we could exploit, then our suggestion would be to create nested queues, so that one can easily subscribe to a parent queue and receive all messages from the queues underneath it (e.g. "subscribe to all 'rain' data in Djibouti" => /djibouti/rain). Of course this is a rather complex problem to tackle; what if the user whats to subscribe to all data from Dorra? We would then need a subscription like /djibouti/dorra, so effectively '/rain' would be under 'djibouti/dorra/rain'. Alternatively, we could move away from MQTT and go to AMQP where messages can define additional attributes/selectors, however we miss the "automatic" subscription to a queue and all its children. The best approach needs to be investigated during the PoC.

4/ "Omar duly sets up the four new queues as requested. Each one is considered to be a data service that must be registered on WIS."
Q: Do we foresee some kind of a registration process here, or this will be automatically picked up by  AWISC's crawling task?

5/ "With Mouktar's assistance to describe the data, Omar creates a new Web page for each data service, describing the data available, the data license, how long data is retained on the queue, how to access it and how authorised users can upload new data. These Web pages also contain structured JSON-LD <script> providing machine-readable metadata."
Q: As in (2), all this could be incorporated into RDSH having the web page(s) being created automatically by Mouktar filling-in a few web-forms.

6/ "Omar adds these new pages to his existing site-map thereby enabling commercial search engines to crawl and index the new content. Similarly, the Authoritative WIS Catalogue will be able to find these new Web pages, extract the relevant metadata and create new records for the data services."
Q: This effectively introduces search results by many different locations which may confuse end-users:
- Mouktar's metadata pages.
- Omar's data pages (which redirect the user back to Mouktar's data)
- Authoritative WIS Catalogue (AWISC)
Omar's queues (if not being offered by AWISC as a central service) should probably only provide the data pipe facility (in an IaaS fashion) but Mouktar is still in control of the data + metadata pages.

7/ "Omar provides Mouktar with a list of trusted Identity Providers (e.g. eduGain, Google etc.) through which he can authenticate."
Q: This will probably need to be implemented via OpenID/SAML2/OAuth, so deploying an RDSH will not be a straightforward process since each RDSH would need to create application IDs with all external IdPs and then register those IdPs into its local RDSH instance.

8/ "[* in this case, we could embed the data in the message itself; it's just a line from a CSV file"
Q: To support posting only updates (and not the complete CSV) implies that either on Mouktar's side or RDSH's side (or AWISC) we implement state management, so that we know what was the last line from the CSV posted to each queue (so that we only post the new ones). This may not be as trivial as it sounds and restricts us to work only with CSVs. What if other partners what to post e.g. images/photos?

9/ "The CSV file is automatically re-published (thanks to the Web server configuration), thereby automating one of Mouktar's many tasks."
Q: This probably implies than the answer in (8) is that state management should be implemented on RDSH. On the other hand, it may be interesting to think about implementing it on Mouktar's side, so that we save bandwidth, considering Mouktar's Internet resources would/may be limited.

10/ "Extension point: value added service based on threshold exceedance on multiple consecutive days".
Q: This is a very interesting extension. IFTTT integration is probably very difficult though as IFTTT is very picky as to which services they support (maybe we could exploit their generic Twitter integration; needs to be further investigated). Another technical complication is that UoD should be able to directly post on Twitter using Djibouti Weather Service account which requires going through the auth process of Twitter (e.g. registering an application, get OAuth2 tokens, etc.).

11/ "Extension point: graphical interaction with CSV data"
Q: This is foreseen by the "Webapp" box in the high-level flow diagram of the Local Dissemination environment.

12/ "Extension point: Web-based data acquisition"
Q: From the description of this extension remains unclear how Mouktar's CSV is updated. RDSH/AWISC should be able to merge Delly's observation to the CSV it already has and serve this merged/updated CSV to end users, but Mouktar needs a way to get these changes/CSV back.

13/ "Extension point: integration of Automatic Weather Station"
Q: If those queues are published/described nowhere, how would end-users find them to subscribe? Technically, it is possible to still describe them in a web page and ask search engines to not index them.

General questions:
A/ In the updated narrative, it seems data and metadata are quite separate entities from the end user's perspective as they can be discovered separately. Considering that data should/is always accompanied by metadata, couldn't data just be an extra "attribute" on the metadata feed pointing the user to the actual location where the data can be retrieved? For example, subscribing to 'djibouti/dorra/rain' you could obtain messages describing the metadata and within such a message you could see that to obtain the actual data you need to subscribe to e.g. 'djibouti/dorra/rain/data'. This also allows us to support different delivery mechanisms in the future - if needed.
B/ Is an architecture solely based on a/multiple AWISCs completely out of the question? With our current/updated design we create many moving parts, asking local contributors (e.g. Mouktar) to operate infrastructure, introducing a new middle-layer (RDSH) requiring qualified (IT) professionals to properly run it, etc.

**Comment by tg4444** [comment]
I have one more question to add to the list.

Concerning the data dissemination, how many queues are required? Based on the narrative, there will be one queue that disseminates both notifications and data, and another one that transmits only data.
Is this the required behavior, or should data only be transmitted using a single queue?
Also, if we wish to provide a notification-only queue, it is a third component, and all of these might need to be multiplied by the number of "channels" we will have (4 in this scenario).

**Comment by rogers492** [comment]
The extra narrative from @6a6d74 and the answers from the scrum on 24/10/17 close #317

**Comment by rogers492** [comment]
Refer to the Djibouti repo for the history of the development of the PoC  https://github.com/OpenWIS/djibouti
