### ISSUE TITLE
Agenda 2018 - TC Meeting

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#400]
>Slot 1 - 29th May 2018 14:00 to 16:00

1. **Opening and introductions**
2.  Layout of Agenda Items
     a.  **Technical infrastructure**: status and plan for future management and operation (including any costs and costs of improvements for SC approval)
     b.  **[Code of conduct](http://openwis.github.io/openwis-documentation/conduct/) and [CLA](http://openwis.github.io/openwis-documentation/rules/A-contributor-license-agreement.html) compliance**: status, review, and recommendations.
     c.  **[Technical rules](http://openwis.github.io/openwis-documentation/tr/) compliance**: status, review, and recommendations
     d.  Project design authority, standards compliance, and release management: status, review and
recommendations
     e.  Key risks and issues of individual OpenWIS Projects: advice the Steering Committee.
     f.  Creation of overall plan
     g.  Forum
     h.  Other items to consider

3. **Technical infrastructure**: status and plan for future management and operation (including any costs and costs of improvements for SC approval)

    **a. Technical infrastructure** 
    i.      Do we have a document (webpage or on github) that describes our infrastructure layout?
    ii.    Do we feel its’ still effective? **Presentation by ED**
    iii. Brief discussion on the environment:  Are we right sized?  Do we need a  bigger/smaller environment? 
    iv.	How do we see the projected 12 month costs changing, if at all?  

    **b.  CI Environment**
    i.	Are we happy with the CI process?  Is there anything we feel we need to change?
   ii.  Discussion about the CI environment

4. **[Code of conduct](http://openwis.github.io/openwis-documentation/conduct/) and [CLA](http://openwis.github.io/openwis-documentation/rules/A-contributor-license-agreement.html) compliance**: status, review, and recommendations.
   a. Review of code of conduct and CLA compliance on web site
   b. Is the code of conduct being applied?  
   c. Is the code of conduct being followed?
  d. Has the CLA and its compliance been used yet by any contributor?
  e. Is there anything we still need to flesh out?
  f. What are our recommendations, if any?

5. **[Technical rules](http://openwis.github.io/openwis-documentation/tr/) compliance**: status, review, and recommendations
   a. Review of technical rules
   b. Are we complying with all technical rules right now?
   c. What’s the status of the technical rules section?
  d. What are our recommendations, if any?

**Comment by jude2018** [comment]
>Slot 2 - 30th May 2018 16:00 to 18:00

6. **Project design authority, standards compliance, and release management**: status, review and 
   recommendations
  a. Review of project design authority, standards compliance and release management
  b. What’s the current status of these?
  c.  How do we show standards compliance?
  d.  Where do we indicate our release management process?
  e.  Do there need to be adjustments to any of these processes or procedures?
  f.  What are our recommendations, if any?

7. **Key risks and issues of individual OpenWIS Projects**: advice the Steering Committee.
    a. Review of current OpenWIS projects
    b. What are the risks associated with each of these projects?
    c. Given current budgets, how do we prioritize ongoing work across all projects?
    d. Now, more than ever, we need more contributions from all founding and strategic members.  How   
       can each contribute?
    e. How do we [ensure quality](https://github.com/OpenWIS/openwis-documentation/issues/395) of our work?  Review the issue and discuss.
    f. How do we show if we’ve met all milestones?  
    g. And did we do what we said we would do?

**Comment by jude2018** [comment]
>Slot 3 - 31st May 2018 09:00 to 11:00

8. **Creation of overall plan**

>_Output_ = review and update of Project Charters from the PMCs.

   a. What does this consist of?

   b. Should it include timeline covering:
       i   POCs; 
       ii  How long OpenWIS 3 will be supported, 
       iii Time between OpenWIS 3 support ending and a version for WIS 2.0 being operational,
       iv Release of first initiation of OpenWIS covering WIS 2.0, 
        v Development of supporting documentation, development of training  
           materials, training?

   c. Work plan for allocation of resources

**Comment by jude2018** [comment]
>Slot 4 - 31st May 2018 11:00 to 13:00

xxxxxx

**Comment by davidpodeur** [comment]
[20180530_TC-presentation_BitTorrent_DPR.pdf](https://github.com/OpenWIS/openwis-documentation/files/2052697/20180530_TC-presentation_BitTorrent_DPR.pdf)

**Comment by solson-nws** [comment]
Talking points from TC to SC

1.  Technical presentations were made regarding the current technical infrastructure and CI process.  The TC recommends the continued use of the existing infrastructure and CI process.  The TC notes that there are current deficiencies with test coverage.  The TC recommendation is to address test coverages with next generation of OpenWIS (i.e OpenWIS2) software due to OpenWIS 3 being in maintenance mode.

2.  For Code of conduct and CLA, the TC recommends internal founding/strategic member organizations who are contributing code, sign CLA agreements by July 2018.  Furthermore, the TC recommends to SC the provisioning of secure storage for CLA signed artifacts.  The TC also passed a resolution on updates to Code of conduct regarding procedural changes for non-compliance.

3.  For Technical rules, the TC took an action to realign/restructure project wiki content and website to streamline access to pertinent information.  Several outstanding issues were closed, and others will be closed after this restructuring.

4.  For Project design authority, standards compliance, and release management, the TC took an action to provide guidance w.r.t. standards compliance as a supplement to Technical rules.  The release management process is captured in the restructuring efforts listed above in item 3.

5.  For Key risks and issues of individual OpenWIS Projects, the TC recommends continued maintenance of OpenWIS 3 for the next 5-6 years.  As apart of the maintenance plan, the TC created a risk mitigation plan to address key influences to OpenWIS software stack.  For the excel2WIS project, no risks have been identified.  The TC view this project as being "dormant" now. Regarding quality measures, the TC will establish a webpage within technical governance that describes repeatable processes/ and where ever possible highlight quality reporting metrics.

6.  Future work.  The TC recommends to SC approve 4 new projects to explore/investigate WIS2 specific requirements.  The TC made a resolution to establish and maintain a cloud VM environment for collaborate development activities for OpenWIS association as required.  The TC will provide the technical specification and associated costs needed to support this environment.  The TC seeks SC approval of this resolution and solution.  Furthermore, the TC recommends to SC that a recurring budget item be established to cover the costs of this cloud environment.

7.  Forum:  The TC is in the process of establishing 1-year license agreement of discourse.  The TC formalized the initial set of categories, subcategories, topics, etc to be used.  The TC recommends the use of openwis.discourse.org as domainname for forum.  The TC recommends to SC that a recurring budget item be established to cover the costs of discourse license.

**Comment by rogers492** [comment]
Meeting complete.
