### ISSUE TITLE
Action-SC-2018-2 support cache in the cloud

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#406]
Support their Permanent Representatives to gain commitment for Cache in the Cloud during the side-meeting planned for the Cache in the Cloud at EC-70, Friday 22 June. Cache in the Cloud project is a precursor to WIS 2.0 - particularly in determining how we can deliver shared services.

**Comment by 6a6d74** [comment]
The side meeting was held during WMO Executive Council 70 (EC-70) to discuss Cache in the Cloud. The meeting was chaired by Michel Jean (Canada), President of the Commission for Basic Systems and a big supporter of WIS 2.0.

Attendees:
Secretariat, France, India, USA, Germany, UK, Japan, S. Korea, China, Australia (plus a few others I couldn't identify)

Germany raised issues about the sustained funding for the Cache in the Cloud as an operational service; citing that a WMO trust fund is not intended for this purpose and is not a good construct. Germany also questioned whether, given the WMO constitution, is the Secretariat legally in a position to manage contracts for operational services.

USA "respects the body of work" and noted that many of the attendees have sponsored experts in developing the proposal. However, their perspective was that the solution fits the WIS architecture designed 10+ years ago, with a centralised cache. USA noted (i) security challenges with any centralised service provision, and (ii) the need to look at other solutions, particularly a more distributed model. USA said it was important to look toward WIS 2.0 and its architecture and requirements before, as a community, we support spending of CHF300k per year on a service like Cache in the Cloud; they "would not stand in the way of a pilot project, but would not themselves participate". 

There was lengthy discussion, lead by Matteo Dell'Acqua about how Cache in the Cloud was a transitional solution, designed to allow progress toward use of cloud for operational services plus use of a financial vehicle to share costs. 

However, the participants (lead again by USA) noted that use of cloud for this kind of service has been proven - and that Cache in the Cloud would not really prove anything.

The participants collectively recognised what the project was trying to achieve, but many wanted the concerns about funding models and technical approach to be addressed before committing funds.

Japan noted that it shared those concerns (funding, technical), and stated it was fully committed to exploitation of the cloud. JMA offered to self-fund a version of Cache in the Cloud leveraging their own cloud platform. 

USA stated their concern about spending money on something that may not be part of the final solution, suggesting that the money would be better spent on bringing in expertise to review and recommend other architectural solutions.

No consensus was achieved during the meeting. As a result, support for the Cache in the Cloud project was not given.

I noted that if we, the WMO Members, cannot agree a consensus approach and a pilot project now, then the only was to proceed will be for Members, either individually or collectively, to develop solutions in this space - which will potentially lead to a fragmented approach and definitely lead to extending the timescales for WIS 2.0 implementation.

What this meeting showed was the disconnect between Experts (all GISCs were represented at TT-GISC where the proposal was discussed) and their senior management. 

As a result of the discussion during the side meeting, an additional resolution was made, encouraging Members (with support from Secretariat) to explore technologies in support of WIS 2.0 implementation:

**Draft Resolution 7.2(1)/4 (EC-70)**

**Requests** the Commission for Basic Systems, in collaboration with the private sector and involving those Members who currently operate GISCs, to analyze the data exchange needs for WIS in order to provide reliable data access to all users considering the availability of new technologies, architectures and communication techniques including cloud based solutions, web services, application programming interfaces, modern messaging protocols etc., and to study how they would support or contribute to the evolution to WIS 2.0 and report back;

**Requests** the Secretary-General to provide the resources to support this work;

**Urges** Members to provide resources for development of potential solutions and feasibility studies.

**Comment by 6a6d74** [comment]
Closed. Cache in the Cloud project was not approved by WMO Executive Council.
