### ISSUE TITLE
Action-TC-2018-09 arrange a demo of the WIS2 PoC at a scrum with ED 

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#445]
A request from David P at the TC in Helsinki for a 10 minute demo

**Comment by jude2018** [comment]
Per TC annual meeting in Helsinki at request and on behlaf of David Podeur

**Comment by jude2018** [comment]
David going look at MS PowerPoint. Close once David has access to the presentation.

**Comment by tg4444** [comment]
@jude2018, since 10 minutes is not that much for a presentation of the PoC, I suggest we demonstrate the following:
1. The RDSH configuration page in LDSH / The LDSH configuration page in RDSH
2. The AWISC configuration page in LDSH / The LDSH configuration page in AWISC
3. An existing dataset (Bibracte) and some quick explanation of its Edit/View pages
4. An AWISC search fetching the above dataset
5. Upload of data for the above dataset, and its retrieval through an MQTT client

I am not certain that we will have enough time even for the above items, but it could be close.

Nevertheless, David could potentially look at the existing documentation in order to get more info:
1. https://github.com/OpenWIS/WIS2-PoC-1/wiki/WIS2-PoC-1-User-Guide
2. https://github.com/OpenWIS/WIS2-PoC-1/wiki/WIS2-PoC-1-Technical-Overview
3. https://github.com/OpenWIS/WIS2-PoC-1/wiki/PoC-demonstration---presentation

**Comment by jude2018** [comment]
@tg4444 .  I am awaiting David's github account being set up.  In the meantime, I will forward your proposal and content of the above post to David and see whether this is enough information and whether a demo is needed.

**Comment by jude2018** [comment]
@tg4444 Is it possible to have an editable version of the video/cartoon that was also created?

**Comment by NMichas** [comment]
We only got a 1 month subscription on PowToon service, just to create the cartoon, so it is not editable anymore. I guess we can reenable the subscription if you need to but keep in mind that you need to maintain an active subscription for as long as you want to be able to edit the video for.

**Comment by davidpodeur** [comment]
I had a look to the existing documentation:
    https://github.com/OpenWIS/WIS2-PoC-1/wiki/WIS2-PoC-1-User-Guide
    https://github.com/OpenWIS/WIS2-PoC-1/wiki/WIS2-PoC-1-Technical-Overview
    https://github.com/OpenWIS/WIS2-PoC-1/wiki/PoC-demonstration---presentation
These are definitely great resources. Thanks.
For now i think it is enough for me. No need for additional demo.

**Comment by jude2018** [comment]
Closed as demo not required by David
