### ISSUE TITLE
Action-TC-2018-16 appoint project lead for openwis core 

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#452]
Leon was the Project Lead.  No formal Lead since since Leon left.  Therefore, TC to decide who the Project Lead is.

**Comment by solson-nws** [comment]
Benjamin and I have thought through potential candidates, and at this time haven't identified an appropriate person, with similar skill sets like Leon, that could be OpenWIS project lead.  Furthermore, since OpenWIS 3 is in maintenance mode, our feeling is that we proceed as a collective group (through PMC), identifying staff members able to work through issues.  Do others have thoughts?

Steve
