### ISSUE TITLE
Update the Articles of Association

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#553]
The SC on 22 May agreed to loosen the scope of OWA for: lobbying, out-reach, and building operational services and introduce the category of ‘contributing’ partner.

Therefore, the following actions are needed:

- [x] Draft changes to the Articles of Association by @remygiraud 
- [x] Review and feedback by mid-July 2019 by ALL
- [x] Review with Legal team and finalise by October 2019 SC.
- [x] Speak to MIchael Robbins regarding this plan @jude2018

**Comment by jude2018** [comment]
Per Board meeting on 23 May - agreed the the decision to not have a specific term for the role of Treasurer should be included in the update to the Articles of Association.  Please also see

**Comment by jude2018** [comment]
Per Board meeting on 23 May - there may a need for an additional membership category, which should be considered as part of reviewing the Articles of Association.  Check implications for budget #556

**Comment by jude2018** [comment]
Meeting held between @remygiraud and Michael Robbins and agreed that Michael Robbins' input wil be needed later this year (c September 2019)

**Comment by jude2018** [comment]
@remygiraud - is there an update on this please?

**Comment by jude2018** [comment]
@remygiraud  - Is there an update on this please?

**Comment by remygiraud** [comment]
@jude2018 @SungsooDO @klsheets @jeremytandy @wqu-bom 
That draft was sent to Jeremy only. Sorry.
Here it is:

[2019-03-13 OpenWIS AISBL Articles Draft v0_7 English RG.docx](https://github.com/OpenWIS/openwis-documentation/files/3969277/2019-03-13.OpenWIS.AISBL.Articles.Draft.v0_7.English.RG.docx)

Please have a look and comment back. This will be discussed in our next SC in March.

**Comment by jude2018** [comment]
SC Mar 2020 - approach is to agree the English version and then translate to French.  So, review text and feedback before the May 2020 SC Annual Meeting

**Comment by jude2018** [comment]
Per SC 26 to 28 may 2020 -it was agreed to review the by-laws to:
 - change the term of aappintment for the Treasurer role to enable training and handover time easier to manage.
- This is addition to the changes to the by-laws to enable receipt of funds to host projects (such as OpenCDMS) .

Ac

**Comment by 6a6d74** [comment]
Comments on the proposed amendments to the byelaws

In general, I'm content with the addition of "Contributing Partners". Some details comments below...

Article 2
Include management of meteorological information in the purpose. I think that this better captures the essence of the OpenCDMS project. I can't see any harm in expanding the scope as proposed.

_1.	The Organization, [...] to: 
(i)	Facilitate collaboration on the development, promotion and sharing of open source software for the **management and** exchange of global meteorological information;.
(ii)	Fostering cooperation and coordination within the meteorological community on the **management and** exchange of global meteorological information;

2.	More specifically the purpose of the Organization is: 
(i)	Coordinating and supporting development of solutions enabling the **management and** exchange of meteorological information;
(ii)	[...] software for the **management and** exchange [...]_

(etc.)

Not sure why Article 3 onward are titled with numerals, e.g. **(iii)** instead of **Article 3**

Article 9, clause 7. 
I don't have any strong views about moving it to the Internal Rules. I guess the question is whether the need to sign a CLA is a fundamental principle of the OpenWIS Association. If so, then it should probably stay as a clause in the Articles.

Article 11 clause 8.
Suggest addition of text stating that the responsibilities of the PMC are defined in the Internal Rules - not sure if we need to, but perhaps we could cite the specific rule/clause?

Article 13 clause 2 and Article 14 clause 1
I've not checked - but I assume these changes to the SC and TC responsibilities are inline with changes we made to the Internal Rules?

Do we need an additional article describing the responsibilities of the PMC? Or is the statement in Article 11 clause 8 sufficient [_yes - I think it probably is if we explicily reference that the PMC responsibilities are define in the Internal Rules as suggested above_]

**Comment by wqu-bom** [comment]
Article 9, clause 7
The fact that the association requires every contributor to sign the CLA makes this clause more like a part of this Article. It should be made more general than just OpenWIS software though. It could be something like this:
9.7 Persons or organizations wishing to contribute to any (software?) project of the Association must sign a Contributor Licence Agreement in a form agreed by the Steering Committee and must comply with all relevant policies approved by the Steering Committee.

Article 10
The discussion on giving the Association the ability to accept finance from third parties should be reflected in this Article. In the amendment, “Contributing Partners” have been added in addition to Strategic and Associate Partners. Is this sufficient to reflect what we want (i.e. accepting finance from third parties)?

Article 11
Agree to the suggestion that the responsibilities of the PMC are defined in the Internal Rules. Clause 8 can be amend to reflect this:
6.8.	A Project Management Committee shall coordinate the technical work related to the project and will report to the Technical Committee. The responsibilities of the Project Management Committee are defined in the Internal Rules.

Article 12
Clause 2(v) states “Agreeing the terms on which the OpenWIS® software shall be licensed;”. This clause may need to be expanded to cover any software from all projects of the Association, not only OpenWIS software.

**Comment by jude2018** [comment]
@SungsooDO, @mvisa , @klsheets , @loiclg  and @kuldeep-sri  (please pass onto Dr SIngh) please feedback

**Comment by remygiraud** [comment]
[2020-09-22.OpenWIS.AISBL.Articles.Draft.v0_8.English.RG.docx](https://github.com/OpenWIS/openwis-documentation/files/5261350/2020-09-22.OpenWIS.AISBL.Articles.Draft.v0_8.English.RG.docx)

Following @6a6d74 and @wqu-bom , please find attached a version 0.8 of the byelaws. I think I have included all the required changes.

**Comment by mvisa** [comment]
Ok for FMI.

**Comment by jude2018** [comment]
Per SC and Board of 29 Sep and 1 Oct:

1. Approval of v0.8 gained by SC 

1. Minor amendments made at the Board to be reflected v0.81 **Action** @remygiraud 

1. Board members to feedback any comments on v0.81 **Action** @loiclg @wqu-bom @6a6d74 @SungsooDO 

1. Another Board meeting if significant changes to v0.81, otherwise **Action** @remygiraud to arrange translation and publication in the Belgian Gazette via notary

**Comment by remygiraud** [comment]
[2020-01-10.OpenWIS.AISBL.Articles.Draft.v0_8_1.English.RG.docx](https://github.com/OpenWIS/openwis-documentation/files/5334804/2020-01-10.OpenWIS.AISBL.Articles.Draft.v0_8_1.English.RG.docx)

After the SC and Board, here is the new version.

**Comment by jude2018** [comment]
Pull Request created to update Articles #604

**Comment by 6a6d74** [comment]
PR #604 now merged. This issue is now resolved. Closing this issue.
