### ISSUE TITLE
CI/CD Development Project

### ISSUE THREAD

**Issue by solson-nws** [OpenWIS/openwis-documentation#578]
This is the omnibus github issue for tracking ED's CI/CD development work

**Comment by EvgeniaPatsoni** [comment]
**This is a small summary of the work done until 15/1/2020 on the OpenWis CI/CD Environment Integration project.**

### Task 1/10 - Analysis:
* Read and analyzed the relevant documentation.
### Task 2/10 - GitHub Tuning:
* Analyzed the OpenWIS GitHub repository (Branches, Tags, Pull requests and Issues).
* Created a new branch for the CICD environment integration, under the name _cicd_integration_, in which all the necessary changes are pushed.
### Task 3/10 - Build Process:
* Created a new module under the name _openwis-libs_, which contains dependencies that are no longer obtainable from the defined Maven repositories. 
* These dependencies have been removed from the parent _.pom_ as well.
* Created the dependencies Maven profile, that is responsible for building the openwis-libs module.
* The required JVM Maven options have been set under the file _.mvn/jvm.config_ in order to be automatically loaded on every build.
* The building process using Maven 3.6.2 and OpenJDK 1.8.0_222 can be executed using the commands: `mvn clean install -Pdependencies,openwis,admin` and `mvn clean install -Pdependencies,openwis,user`.
### Task 4/10 - Travis CI Integration:
* OpenWIS project had already been integrated with Travis CI. For the updated integration, Travis uses Maven version 3.6.2 and OpenJDK 1.8.0.2_222. The updated _travis.yml_ script can be found [here](https://github.com/OpenWIS/openwis/blob/cicd_integration/.travis.yml).
* For the test integration, the script was successfully executed in ~ 10 minutes.

**Comment by EvgeniaPatsoni** [comment]
**This is a followup of the work done until 24/1/2020 on the OpenWis CI/CD Environment Integration project.**

# Task 5.1 - Continuous Delivery:
- Created a Continuous Delivery environment that supports secure communication with a remote server.
- After the build processes succeeds, nine (9) build artifacts will be copied to the remote server over SSH.

# Task 5.2 - Travis Configuration:
- Finalized the configuration of the _.travis_ file which can be found [here](https://travis-ci.org/OpenWIS/openwis/jobs/641275031/config).
- The Travis encoded SSH key is repository dependent and cannot be used by other repositories. If we try to use it from another repository the build will fail.
- It is recommended to apply the delivery process in a branch where Pull Requests are restricted, in order to avoid delivery of possible malicious code.


# Task 6 - Unit & Integration Test Reports
- In total ninety-three (93) tests are running during the build process.
- Four (4) tests are being skipped due to the _@ Ignore_ annotation they contain.
- Added _Java Code Coverage (jacoco)_ tool which generates reports of the code coverage, that is measurements of how many lines of codes are executed during the unit and integration tests.
- _jacoco-coverage_ Maven profile has been included in the parent pom.xml file.
- The automated tests will be run and the reports will be saved under the target/site folder of each module which includes tests by executing the command `mvn clean install -Pdependencies,openwis,jacoco-coverage`
- Feedback required: OpenWIS needs to provide a way to execute _openwis-dataservice-server-ejb_ module

**Comment by EvgeniaPatsoni** [comment]
This is a followup of the work done until 31/1/2020 on the OpenWis CI/CD Environment Integration project.

# Task 7.1/10 - Sonar Cloud Integration
The steps followed in order to integrate the OpenWIS project with SonarCloud were:

- Login to https://sonarcloud.io with a GitHub account who has Administrator permissions on the OpenWIS GitHub organization
- Create a new SonarCloud organization and connect it with the related GitHub Organization
- Select the specific repositories which will be analyzed (i.e. OpenWIS) and provide Read and Write access to SonarCloud
- Generate the SonarCloud organization key, which will be used to trigger the analysis (i.e. openwis)
- Choose the free integration plan, instead of the paid plan which provides you the option to have private analysis reports
- Select the option ‘Analyze new project’, the OpenWIS project and select ‘Set Up’
- Select Analysis with Travis CI
- Go to the Security panel of your account and generate a token to be used for the analysis: https://sonarcloud.io/account/security/. User must have ‘Execute Analysis’ permissions for the Organization: https://sonarcloud.io/organizations/openwis/permissions
- Update OpenWIS pom.xml to include the following plugin under the PluginManagement section: 
```
<plugin>	
    <groupId>org.sonarsource.scanner.maven</groupId>	
    <artifactId>sonar-maven-plugin</artifactId>	
    <version>3.7.0.1746</version>
</plugin>
```
- After having build the project with the Jacoco-Coverage Maven profile, execute the analysis with the command:
`mvn sonar:sonar -Popenwis,admin,user -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_KEY}`
(actual values should be used here, but are not displayed for security reasons)
- SonarCloud analysis for the OpenWIS project can be found [here](https://sonarcloud.io/dashboard?id=OpenWIS_openwis)
- In order to reduce the number of code smells, that was initially 90k, we excluded any external JS libraries from the analysis and only allowed OpenWIS JS scripts to be analyzed. Changes can be found in the [pom.xml ](https://github.com/OpenWIS/openwis/blob/cicd_integration/openwis-metadataportal/openwis-portal/pom.xml) of the openwis-metadataportal module.

# Task 7.2/10 - OWASP Dependency Check
- OWASP Dependency-Check tool is integrated using Maven with the following lines:
```
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>${dependency-check-maven.version}</version>
    <configuration>
    <format>ALL</format>
    <failOnError>false</failOnError>
    </configuration>
</plugin>
```
- In order to run the OWASP Dependency Check, the following command must be run:
` mvn -Popenwis,user,admin org.owasp:dependency-check-maven:aggregate`

# Task 8/10 - SonarCloud & Travis-CI Integration 
- Navigate to the [settings ](https://travis-ci.org/OpenWIS/openwis/settings)panel of the Travis-CI integration and add the SonarCloud information as secret parameters
- Update the travis.yml file to include the analysis step:
`mvn sonar:sonar -Popenwis,admin,user -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_KEY}`
- Since Travis-CI supports the generation of maximum 4MB of logs per job, the option –q was added in the build scripts in order to reduce the volume of the generated Maven logs and skip the job failure

**Comment by EvgeniaPatsoni** [comment]
# Task 9.1/10 - SonarCloud & Travis-CI Integration - Updated 
- We updated Travis-CI integration to be user-independent with the following steps:
1. Delete the SonarCloud analysis that was generated in the previous phase.
2. Navigate to https://sonarcloud.io/projects/create, select the OpenWIS repository under OpenWIS Organization to be analyzed, and click Set Up.
3. After the project has been created click on Travis CI 
4. Encrypt the key that will appear on your screen by executing the following command inside the OpenWIS directory: 
travis encrypt <key> 
5. Add the secure value in the travis.yml file
6. Add the following command under the script section:
    ```
    mvn sonar:sonar -Popenwis,admin,user -Dsonar.projectKey=OpenWIS_openwis
    ```

# Task 9.2/10 - Test Procedure
- All the current work was pushed at the cicd_integration branch. 
In order to completely test the CICD process, all the work was merged into the master branch, by executing:
    ```
    git merge cicd_integration 
    git push
    ```
- Since the repository was configured in the past with both travis-ci.org and travis-ci.com platforms, the travis-ci.com integration was removed, by disabling its access to the GitHub organization from the administration panel. Only the travis-ci.org integration is active, which can be found here.
- Seven test branches (now deleted) and the related pull requests (now closed) have been created, in order to test the complete process
- Pull Request 5 breaks the maven build process, and as a result the Travis-CI job.
- Pull Request 7 duplicates one existing class with 2 code smells and 2 bugs, so as a result the Sonar analysis fails.
- The Pull Request 3 adds a new txt file at the source code.


# Task 10/10 - Knowledge Transfer Preparation
- The ED proposed training agent was discussed

**Comment by jude2018** [comment]
Please note #195

**Comment by solson-nws** [comment]
This issue can be closed.  CI/CD contract is now complete, training has been conducted and the contract with ED will be closed out.
