### ISSUE TITLE
OpenWIS 3.x Infrom TC and SC of how MFI code changes will be made visible

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#587]
Per SC on 26 and 28 May 2020 - There is a need for TC and SC members to understand the changes being made by MFI on the OpenWIS 3.x to inform the TC work plan, including work to be done on middleware and investigations into OpenAM and OpenDJ replacements (Keycloak?) and Geoenetwork inevestigations.

**Comment by remy-gibault** [comment]
MFI has just installed new beta release of OpenWIS software at Singapore.
UAT is scheduled for August 2020.

Middleware upgrade has been achieved.

Here after is the list of upgraded components: 

| COTS  | New Version (Singapore) | Former Version (Openwis 3.14) |
| ------------- | ------------- |------------- |
| OS | RedHat 7.7 | CentOS 6.5 |
| PostgreSQL | 10 without POSTGIS | 9.2 with POSTGIS |
| OpenDJ | Community 4.4.1 With   Java 8 | 2.6.0 |
| OpenAM | Community   14 With Java 8 ( 2FA through OAUTH ) | 12.0.0 |
| Java | Java   8 | Java   8 |
| JBOSS | WildFly 19 | 7.1 |
| Tomcat | 9 | 7 |
| SolR | 8.2 standalone | 1.4.1 |

**Comment by jude2018** [comment]
@benjaminsaclier and @solson-nws are you OK for this issue to be closed?

**Comment by solson-nws** [comment]
Update on Issue:

Hi Steve,

Your understanding is correct.
MFI will upload the Singapore version to the OpenWIS github repo as a new candidate release at no cost for the OpenWIS Association.
I will let you know the target date later on (about august/sept).
We are currently deploying the software on the UAT environment. I would like to pass all tests before providing the release to the association.

I'd like to bring to your attention that MFI has no technical expertise on this new release. MFI relies on Akka for all technical aspects of OpenWIS software. 
MFI can offer a couple of days of assistance from Akka experts in order to help the OpenWIS Association CI/CD team members to familiarize themselves with the Singapore release.
MFI/Akka is not willing to be more involved in the automated build and release process.  

Adapting the RFP based on experience gained in the analysis of this candidate release sounds good to me.
MFI/Akka are very likely to bid on this middleware RFP.

I hope that the message is clear and that it is well received.

Kind regards

------------------------------

Hi Steve,

I'd like to rectify the wording of this sentence:  "MFI/Akka are very likely to bid on this middleware RFP".
Of course, Akka would be the bidder in such case.

Regards  

----------------------------------------------------------

Hello Remy!

And congrats to you and the team for your successes!  I just want to clarify a few things here so we may proceed with plans and next steps.

So, to clarify, MFI will upload the Singapore version to the OpenwIS github repo as a new candidate release.  Then the OpenWIS Association CI/CD team members will work with MFI to understand the differences between the current 3.14.9 and Singapore releases (including peer review) to ensure everyone is comfortable with the Singapore release before initiating the automated build and release process.  This will be done at no cost to the OpenWIS Association.  Then, the TC will modify the middleware RFP based on this new release.  The intent is to allow MFI/Akka and others to be able to bid on this middleware RFP.  Let me know if I misinterpreted anything Remy!

Thanks!

Steve

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier is there an update on updating the RFP ?

**Comment by jude2018** [comment]
Close and tracked tthrough https://github.com/OpenWIS/openwis-documentation/issues/590 and https://github.com/OpenWIS/openwis-documentation/issues/593 and referenced in https://github.com/OpenWIS/openwis-documentation/issues/592
