### ISSUE TITLE
review of CLA, form and process

### ISSUE THREAD

**Issue by 6a6d74** [OpenWIS/openwis-documentation#98]
Comments on the [**CLA**](https://github.com/OpenWIS/openwis-documentation/blob/gh-pages/rules/A-contributor-license-agreement.md)

When we discussed this, I suggested that we want to be able to refer to a specific version of the CLA using a URL; e.g. `http://openwis.github.io/openwis-documentation/static/CLA/CLAv1.html`

So embedded within the Internal Rules, [Annex A](http://openwis.github.io/openwis-documentation/rules/A-contributor-license-agreement.html) would list all the specific versions of the CLA _and_ include the text of the current CLA. 

(it may be possible to write the CLA text as an 'include' so we avoid duplicating text (with the possibility of errors) and include the text in both IR Annex A and the specific version.

Also: 

[Line 28](https://github.com/OpenWIS/openwis-documentation/blob/gh-pages/rules/A-contributor-license-agreement.md#L28) currently states:

> Contributions shall be made by submitting a Pull Request to the relevant project repository within [GitHub](https://github.com/). Information on using Pull Requests can be found in the [GitHub help](https://help.github.com/articles/using-pull-requests/) pages. When you have created your Pull Request, please contact the OpenWIS Community Manager via [email](mailto:contact@openwis.io) to request a CLA form. Once your CLA has been sucessfully processed, your Pull Request will be considered.

(noting the typo: _sucessfully_)

Suggest the following:

> Contributions shall be made by submitting a Pull Request to the relevant project repository within [GitHub](https://github.com/). Information on using Pull Requests can be found in the [GitHub help](https://help.github.com/articles/using-pull-requests/) pages. Prior to submitting your first Pull Request you must send a completed [CLA form](http://openwis.github.io/openwis-documentation/static/CLA/CLAform.html) to the OpenWIS Community Manager via [email](mailto:contact@openwis.io). A Pull Request will only be reviewed if the Contributor has submitted the CLA form.

[Line 58](https://github.com/OpenWIS/openwis-documentation/blob/gh-pages/rules/A-contributor-license-agreement.md#L58) refers to GPL:

> subsequent version of the GPL approved

I think we need to be more general. 

[Line 118](https://github.com/OpenWIS/openwis-documentation/blob/gh-pages/rules/A-contributor-license-agreement.md#L118) only makes sense to include in the Annex A (current) copy. The specific version doesn't need this link.

**Comment by rogers492** [comment]
From @wqu-bom  22/11/16
Based on your advice that the CLA is to be used by third parties contribution to OpenWIS (with the Bureau ultimately a recipient of material provided under it) I make the following comments: 

•	The licence in clause 2 is irrevocable. This is only an issue for the Bureau, if the Bureau itself is contributing material (which I understand it is not). 
•	There are a number of errors in drafting (e.g. not capitalising ‘you’ and ‘your’ throughout when it is a defined and capitalised term)
•	There is no indemnity specifically for IP infringement (see clause 7) – but instead an indemnity for fraudulent or negligent misrepresentation. So for circumstances of misrepresentation that falls short of those thresholds, the OpenWIS Association will not have an indemnity. That is, there is a gap in the indemnity protection. This may ultimately expose the Bureau to unnecessary financial liability if the Bureau is responsible in part for any liability that OpenWIS has to pay.  
•	Do clause 4 and 5 conflict in some circumstances?
•	Compulsory mediation in clause 8 can be a potentially expensive way of settling disputes. If the Bureau is in part responsible for the costs of the OpenWIS Association, then making mediation voluntary rather than compulsory may be of benefit.

**Comment by rogers492** [comment]
Hi Paul,

1.	The licence needs to be irrevocable. This is the case for any Open Source project. Were the licence revocable, the community would be faced with having to rip out contributions that may have been through many iterations and been worked upon (and used by) many other people. This is a obviously a huge (and very disruptive) task.

All major Open Source projects of which I am aware ask for an irrevocable licence over contributions in order to avoid having to disentangle contributions at a later date. A contribution that is at risk of being taken back cannot, IMHO, be accepted.

To be clear, this does not commit any contributor to make future contributions. It only means that they cannot revoke permission for contributions they have already made to be used in the way described in the CLA. I would hope that anyone wishing to contribute to an Open Source project would be comfortable with these principles. It may just need a little explaining.

2.	Agreed. I think this is an error in transposition to the website. “You” and “Your” should be capitalised.

3.	I agree, but the association needs to take a view about the level of risk it is comfortable with. I recall that we have previously discussed this point and decided that asking for a full IP infringement indemnity would act as a barrier to take-up. It was felt that any liability that arose was likely to do so because someone made a statement that was untrue re: the originality of their contribution. Whilst it’s possible that an innocent misrepresentation could be made, the gap is quite narrow:
Fraudulent misrepresentation: where a false representation has been made knowingly, or without belief in its truth, or recklessly as to its truth.
Negligent misrepresentation: a representation made carelessly and in breach of duty owed by Party A to Party B to take reasonable care that the representation is accurate. If no "special relationship" exists, there may be a misrepresentation under section 2(1) of the Misrepresentation Act 1967 where a statement is made carelessly or without reasonable grounds for believing its truth. 
Innocent misrepresentation: a representation that is neither fraudulent nor negligent. 
Only the final type isn’t covered. It would only come into play is reasonable care was taken to ensure a statement was true, but it still turned out to be false.

This is an agreement under Belgian law, but I understand that the principles are broadly the same there.

The association does enjoy limited liability and so none of the members would be on the hook for any liability. In a worst case scenario, the association would have to go into liquidation.

4.	I don’t think so. Clause 4 is about entitlement to grant the licence. Clause 5 is about originality and non-assignment. I can’t see that they conflict.

5.	Mediation is, by definition, not compulsory. No party can be compelled to mediate. However, the courts here (and I know this to be the case in Belgium too) do require that parties consider ADR before resorting to litigation. Clause 8 and 9 are an attempt to formalise this obligation to consider mediation. It also means that (aside from urgent applications) no one can go to court for 90 days.

I would also say that mediation is invariably cheaper than litigation in cases where it leads to settlement (and settlement rates at EPANI are very high). Lord Neuberger summed up the situation well in his speech to the Civil Mediation Conference last year:

https://www.supremecourt.uk/docs/speech-150512-civil-mediation-conference-2015.pdf

If it helps, I am an Accredited Civil and Commercial Mediator – though I suspect I would not be sufficiently neutral to act in the majority of disputes that may involve the association.

Best regards,

Michael Robbins DipHE LLB (Hons) PGDip (Legal Practice)

**Comment by rogers492** [comment]
The whole process of refining our CLA mgt is covered by a bunch of actions: #202 #201 #200 #190 #189 #156 #155 #98

**Comment by rogers492** [comment]
Hi Paul,

this was discussed internally at FMI already in November. Somehow the answer got stuck in my mailbox.. Anyway, at that time there were some indemnity issues raised, but based on comments (regarding limited liability etc.) from Michael Robbins in issue 98 I think from FMI point of view we are good to go with this.

 Mikko

-- 
Mikko Visa, Head of Group
Development of Services, Finnish Meteorological Institute

**Comment by rogers492** [comment]
From: ssdo@korea.kr [mailto:ssdo@korea.kr] 
Sent: 17 April 2017 05:32
To: Rogers, Paul
Cc: "openwis-sc@meteo.fr"
Subject: RE: [openwis-sc] Action for SC delegates - CLA process: Legal review
 
Hello Paul,
KMA has no objection to the CLA.
Everything is OK for us to comment on it.
 
Many thanks,
Sungsoo

**Comment by rogers492** [comment]
Responses so far:
Accepted: UKMO, MF, FMI, KMA
Questions: BoM
No response: NWS, MFI

**Comment by rogers492** [comment]
Hi @klsheets and @remy-gibault - Do you have any response on the legal review of the CLA? BoM have raised some questions (see above) and I would like to add in any from yourselves for final consideration.
thanks, Paul

**Comment by rogers492** [comment]
* [BoM question 1] The licence in clause 2 is irrevocable. This is only an issue for the Bureau, if the Bureau itself is contributing material (which I understand it is not).
* [UKMO answer 1] The licence needs to be irrevocable. This is the case for any Open Source project. Were the licence revocable, the community would be faced with having to rip out contributions that may have been through many iterations and been worked upon (and used by) many other people. This is a obviously a huge (and very disruptive) task. All major Open Source projects of which I am aware ask for an irrevocable licence over contributions in order to avoid having to disentangle contributions at a later date. A contribution that is at risk of being taken back cannot, IMHO, be accepted.

* To be clear, this does not commit any contributor to make future contributions. It only means that they cannot revoke permission for contributions they have already made to be used in the way described in the CLA. I would hope that anyone wishing to contribute to an Open Source project would be comfortable with these principles. It may just need a little explaining.
* [Outcome 1] No change to the CLA.

**Comment by rogers492** [comment]
* [BoM question 2] There are a number of errors in drafting (e.g. not capitalising ‘you’ and ‘your’ throughout when it is a defined and capitalised term)
* [UKMO answer 2] Agreed. I think this is an error in transposition to the website. “You” and “Your” should be capitalised.
* [Outcome 2] CLA updated to capitalise defined terms.

**Comment by rogers492** [comment]
* [BoM question 3] There is no indemnity specifically for IP infringement (see clause 7) – but instead an indemnity for fraudulent or negligent misrepresentation. So for circumstances of misrepresentation that falls short of those thresholds, the OpenWIS Association will not have an indemnity. That is, there is a gap in the indemnity protection. This may ultimately expose the Bureau to unnecessary financial liability if the Bureau is responsible in part for any liability that OpenWIS has to pay.
* [UKMO answer 3] I agree, but the association needs to take a view about the level of risk it is comfortable with. I recall that we have previously discussed this point and decided that asking for a full IP infringement indemnity would act as a barrier to take-up. It was felt that any liability that arose was likely to do so because someone made a statement that was untrue re: the originality of their contribution. Whilst it’s possible that an innocent misrepresentation could be made, the gap is quite narrow:
    * Fraudulent misrepresentation: where a false representation has been made knowingly, or without belief in its truth, or recklessly as to its truth.
    * Negligent misrepresentation: a representation made carelessly and in breach of duty owed by Party A to Party B to take reasonable care that the representation is accurate. If no "special relationship" exists, there may be a misrepresentation under section 2(1) of the Misrepresentation Act 1967 where a statement is made carelessly or without reasonable grounds for believing its truth.
    * Innocent misrepresentation: a representation that is neither fraudulent nor negligent.

* Only the final type isn’t covered. It would only come into play if reasonable care was taken to ensure a statement was true, but it still turned out to be false.

* This is an agreement under Belgian law, but I understand that the principles are broadly the same there.

* The association does enjoy limited liability and so none of the members would be on the hook for any liability. In a worst case scenario, the association would have to go into liquidation.

* [Outcome 3] No change to the CLA.

**Comment by rogers492** [comment]
* [BoM question 4] Do clause 4 and 5 conflict in some circumstances?
* [UKMO answer 4] I don’t think so. Clause 4 is about entitlement to grant the licence. Clause 5 is about originality and non-assignment. I can’t see that they conflict.
* [Outcome 4] No change to CLA.

**Comment by rogers492** [comment]
* [BoM question 5] Compulsory mediation in clause 8 can be a potentially expensive way of settling disputes. If the Bureau is in part responsible for the costs of the OpenWIS Association, then making mediation voluntary rather than compulsory may be of benefit.
* [UKMO answer 5] Mediation is, by definition, not compulsory. No party can be compelled to mediate.
* However, the courts here (and I know this to be the case in Belgium too) do require that parties consider ADR before resorting to litigation. Clause 8 and 9 are an attempt to formalise this obligation to consider mediation. It also means that (aside from urgent applications) no one can go to court for 90 days.

* I would also say that mediation is invariably cheaper than litigation in cases where it leads to settlement (and settlement rates at EPANI are very high). Lord Neuberger summed up the situation well in his [speech to the Civil Mediation Conference last year](https://www.supremecourt.uk/docs/speech-150512-civil-mediation-conference-2015.pdf).

* If it helps, I am an Accredited Civil and Commercial Mediator – though I suspect I would not be sufficiently neutral to act in the majority of disputes that may involve the association.

* [Outcome 5] No change to CLA.

**Comment by rogers492** [comment]
I have updated the CLA based on the feedback received so far and I am now closing this issue. If there is any further feedback, please open a new issue.

**Comment by rogers492** [comment]
Our legal council just got back to use with feedback on the CLA. 

Here's the summary and I've attached the full doc with their edits

see attached suggested changes to the contributor license. I'd be happy to discuss the rationale behind any changes and to consider any counter proposals by the OpenWIS Association.

I'd also just like to reiterate, we'll need to be sure that if we provide code that was co-developed with non-NOAA Federal employees, that we ensure we have any necessary rights and permissions to share that code under this license agreement. If that is relevant, I'd be happy to discuss that further as well.

[OpenWIS CONTRIBUTOR LICENSE AGREEMENT_GC edits.pdf](https://github.com/OpenWIS/openwis-documentation/files/1115806/OpenWIS.CONTRIBUTOR.LICENSE.AGREEMENT_GC.edits.pdf)


Kari

**Comment by rogers492** [comment]
I've asked Michael Robbins to respond.

**Comment by rogers492** [comment]
From Michael 6 July 2017:
Hi Paul,

I don’t think that the bulk of this is acceptable, I’m afraid. As a rule, the CLA shouldn’t be viewed as something that is negotiable. It is a standard document that all contributors need to abide by. We cannot have wildly different CLAs for each contributor. Having said that:

Happy to use “CLA” instead of “Agreement” throughout (CLA is the defined term);

The Association can’t accept changes to the definition of “Work” – this has to remain consistent across the board. I certainly don’t think it should countenance the removal of “electronic” from the definition and I’d also be worried about removing “verbal”, given the information exchanges at DevCons and other meetings ;

The changes to clauses 3 and 6 are OK. In Clause 5, “licence” is correct for British English (“license” is a verb) – but this isn’t a big deal;

The Association cannot do without the indemnity in Clause 7 (the agreement loses much of its teeth without this) and I don’t believe it can accept the changes to Clause 8 or deletion of Clause 9 – the dispute resolution procedure has to be consistent for all. It should be noted that the indemnity covers only fraud and negligent misrep. in any event – not innocent mistakes;

The addition to Clause 10 is probably OK (subject to what I’ll say later about applicable law...);

The change re: costs in Clause 11 is not acceptable. The “further assurance” clause loses all utility if it’s made subject to availability of appropriated funds. It’s an absolute obligation (as is everything else in the agreement) and it can’t be conditioned in this way; and

The Association cannot agree to delete the choice of law clause. Again, this needs to be remain consistent for all and we need to be clear that, as the Association is constituted under Belgian law, it is Belgian law that governs the CLA. 

Happy to speak with SC/Board members if desired.

Best regards,
Michael

Michael Robbins DipHE LLB (Hons) PGDip (Legal Practice) GCILEx
Legal Manager - IPR and Partnerships

**Comment by rogers492** [comment]
Closed after SC meeting Dec 2017. The SC decided to accept the CLA as-is.
